export const FETCH_TRANSACTIONS_REQUEST = 'FETCH_TRANSACTIONS_REQUEST';
export const FETCH_TRANSACTIONS_SUCCESS = 'FETCH_TRANSACTIONS_SUCCESS';
export const FETCH_TRANSACTIONS_FAILED = 'FETCH_TRANSACTIONS_FAILED';

export const SET_SELECTED_TRANSACTION = 'SET_SELECTED_TRANSACTION';
export const SET_SORTING_TRANSACTION = 'SET_SORTING_TRANSACTION';
